// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: lib/constant.proto

package corpus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Corpus int32

const (
	Corpus_CORPUS_UNSPECIFIED Corpus = 0
	Corpus_CORPUS_UNIVERSAL   Corpus = 1
	Corpus_CORPUS_WEB         Corpus = 2
	Corpus_CORPUS_IMAGES      Corpus = 3
	Corpus_CORPUS_LOCAL       Corpus = 4
	Corpus_CORPUS_NEWS        Corpus = 5
	Corpus_CORPUS_PRODUCTS    Corpus = 6
	Corpus_CORPUS_VIDEO       Corpus = 7
)

// Enum value maps for Corpus.
var (
	Corpus_name = map[int32]string{
		0: "CORPUS_UNSPECIFIED",
		1: "CORPUS_UNIVERSAL",
		2: "CORPUS_WEB",
		3: "CORPUS_IMAGES",
		4: "CORPUS_LOCAL",
		5: "CORPUS_NEWS",
		6: "CORPUS_PRODUCTS",
		7: "CORPUS_VIDEO",
	}
	Corpus_value = map[string]int32{
		"CORPUS_UNSPECIFIED": 0,
		"CORPUS_UNIVERSAL":   1,
		"CORPUS_WEB":         2,
		"CORPUS_IMAGES":      3,
		"CORPUS_LOCAL":       4,
		"CORPUS_NEWS":        5,
		"CORPUS_PRODUCTS":    6,
		"CORPUS_VIDEO":       7,
	}
)

func (x Corpus) Enum() *Corpus {
	p := new(Corpus)
	*p = x
	return p
}

func (x Corpus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Corpus) Descriptor() protoreflect.EnumDescriptor {
	return file_lib_constant_proto_enumTypes[0].Descriptor()
}

func (Corpus) Type() protoreflect.EnumType {
	return &file_lib_constant_proto_enumTypes[0]
}

func (x Corpus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Corpus.Descriptor instead.
func (Corpus) EnumDescriptor() ([]byte, []int) {
	return file_lib_constant_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_constant_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_lib_constant_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_lib_constant_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_lib_constant_proto protoreflect.FileDescriptor

var file_lib_constant_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6c, 0x69, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x77, 0x65, 0x73, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61,
	0x67, 0x65, 0x2a, 0xa3, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x72, 0x70, 0x75, 0x73, 0x12, 0x16, 0x0a,
	0x12, 0x43, 0x4f, 0x52, 0x50, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4f, 0x52, 0x50, 0x55, 0x53, 0x5f,
	0x55, 0x4e, 0x49, 0x56, 0x45, 0x52, 0x53, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x43,
	0x4f, 0x52, 0x50, 0x55, 0x53, 0x5f, 0x57, 0x45, 0x42, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x43,
	0x4f, 0x52, 0x50, 0x55, 0x53, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x53, 0x10, 0x03, 0x12, 0x10,
	0x0a, 0x0c, 0x43, 0x4f, 0x52, 0x50, 0x55, 0x53, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x04,
	0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x52, 0x50, 0x55, 0x53, 0x5f, 0x4e, 0x45, 0x57, 0x53, 0x10,
	0x05, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x52, 0x50, 0x55, 0x53, 0x5f, 0x50, 0x52, 0x4f, 0x44,
	0x55, 0x43, 0x54, 0x53, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4f, 0x52, 0x50, 0x55, 0x53,
	0x5f, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x07, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x65, 0x78, 0x62, 0x72, 0x6f, 0x63, 0x68,
	0x75, 0x2f, 0x61, 0x77, 0x65, 0x73, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x2f, 0x63, 0x6f, 0x72, 0x70, 0x75, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lib_constant_proto_rawDescOnce sync.Once
	file_lib_constant_proto_rawDescData = file_lib_constant_proto_rawDesc
)

func file_lib_constant_proto_rawDescGZIP() []byte {
	file_lib_constant_proto_rawDescOnce.Do(func() {
		file_lib_constant_proto_rawDescData = protoimpl.X.CompressGZIP(file_lib_constant_proto_rawDescData)
	})
	return file_lib_constant_proto_rawDescData
}

var file_lib_constant_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lib_constant_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_lib_constant_proto_goTypes = []interface{}{
	(Corpus)(0),  // 0: awesomepackage.Corpus
	(*User)(nil), // 1: awesomepackage.User
}
var file_lib_constant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lib_constant_proto_init() }
func file_lib_constant_proto_init() {
	if File_lib_constant_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lib_constant_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lib_constant_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lib_constant_proto_goTypes,
		DependencyIndexes: file_lib_constant_proto_depIdxs,
		EnumInfos:         file_lib_constant_proto_enumTypes,
		MessageInfos:      file_lib_constant_proto_msgTypes,
	}.Build()
	File_lib_constant_proto = out.File
	file_lib_constant_proto_rawDesc = nil
	file_lib_constant_proto_goTypes = nil
	file_lib_constant_proto_depIdxs = nil
}
